# Generated by Django 5.1.1 on 2024-09-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Job', models.CharField(max_length=250)),
                ('Years_work', models.IntegerField(max_length=5)),
                ('Completed_projects', models.IntegerField(max_length=5)),
                ('Satisfied_costomers', models.IntegerField(max_length=5)),
            ],
        ),
    ]
