# Generated by Django 5.1.1 on 2024-09-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user_portfolio',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='Completed_projects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='Satisfied_costomers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='Years_work',
            field=models.IntegerField(),
        ),
    ]
