# Generated by Django 5.1.1 on 2024-09-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills_user_portfolio_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_portfolio',
            name='Completed_projects',
        ),
        migrations.RemoveField(
            model_name='user_portfolio',
            name='Satisfied_costomers',
        ),
        migrations.RemoveField(
            model_name='user_portfolio',
            name='Years_work',
        ),
    ]
