# Generated by Django 5.1.1 on 2024-09-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_user_portfolio_completed_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Linkbigint', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user_portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('Level', models.CharField(max_length=255)),
                ('G_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user_portfolio')),
            ],
        ),
    ]
