# Generated by Django 5.1.1 on 2024-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_portfolio',
            name='Years_work',
            field=models.IntegerField(null=True),
        ),
    ]
