# Generated by Django 5.1.1 on 2024-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_user_portfolio_years_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_portfolio',
            name='Completed_projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_portfolio',
            name='Satisfied_costomers',
            field=models.IntegerField(null=True),
        ),
    ]
